### ISSUE TITLE
Cant use osmc plugin updates on a leap year on feb 29th

### ISSUE THREAD

**Issue by vStone** [osmc/osmc#283]
```
12:49:48  70.613045 T:1797264368   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: day is out of range for month
                                            Traceback (most recent call last):
                                              File "/usr/share/kodi/addons/script.module.osmcsetting.updates/service.py", line 38, in <module>
                                                m = update_service.Main()
                                              File "/usr/share/kodi/addons/script.module.osmcsetting.updates/resources/lib/update_service.py", line 185, in __init__
                                                self.scheduler = sched.SimpleScheduler(self.s)
                                              File "/usr/share/kodi/addons/script.module.osmcsetting.updates/resources/lib/simple_scheduler.py", line 16, in __init__
                                                self.trigger_time 	= datetime.datetime.now().replace(year=2222)	# the time of the next update check
                                            ValueError: day is out of range for month
                                            -->End of Python script error report<--
```

**Comment by samnazarko** [comment]
Already fixed in 75a6648f1477aa49c2e55aa901aca31b72d8796b.
