### ISSUE TITLE
ImportError: No module named urllib3.exceptions

### ISSUE THREAD

**Issue by jose1711** [osmc/osmc#473]
OSMC is reporting a problem on startup. from debug log:

```
11:15:36.759 T:1646260992  NOTICE: Skin Helper Service --> Skin Helper Service version 1.1.3 started
11:15:37.005 T:1654649600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named urllib3.exceptions
                                            Traceback (most recent call last):
                                              File "/usr/share/kodi/addons/service.osmc.settings/service.py", line 26, in <module>
                                                import resources.lib.osmc_main as m
                                              File "/usr/share/kodi/addons/service.osmc.settings/resources/lib/osmc_main.py", line 52, in <module>
                                                import osmc_walkthru
                                              File "/usr/share/kodi/addons/service.osmc.settings/resources/lib/osmc_walkthru.py", line 11, in <module>
                                                import requests
                                              File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 60, in <module>
                                                from .packages.urllib3.exceptions import DependencyWarning
                                            ImportError: No module named urllib3.exceptions
                                            -->End of Python script error report<--
```
This happened after OSMC update.
```
 dpkg -l python-requests        
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                  Version                 Architecture            Description
+++-=====================================-=======================-=======================-================================================================================
ii  python-requests                       2.12.4-1                all                     elegant and simple HTTP library for Python2, built for human beings
```

**Comment by samnazarko** [comment]
Closing if this is not an OSMC issue.

**Comment by jose1711** [comment]
for the record: finally resolved by `pip install --upgrade requests`. this upgraded `requests` from 2.12.4 to 2.21.0.
