### ISSUE TITLE
Trouble with WIFI

### ISSUE THREAD

**Issue by Arndorferd** [osmc/osmc#741]
Cant connect to wifi getting this error in logs

2023-07-29 04:06:21.681 T:557      info <general>: Loading skin file: Settings.xml, load type: KEEP_IN_MEMORY
2023-07-29 04:06:25.294 T:557      info <general>: Loading skin file: /usr/share/kodi/addons/service.osmc.settings/resources/skins/Default/1080i/settings_gui.xml, load type: LOAD_ON_GUI_INIT
2023-07-29 04:06:25.432 T:667     error <general>: EXCEPTION: Non-Existent Control 300
2023-07-29 04:06:27.167 T:557      info <general>: Loading skin file: /usr/share/kodi/addons/script.module.osmcsetting.networking/resources/skins/Default/1080i/network_gui.xml, load type: LOAD_ON_GUI_INIT
2023-07-29 04:06:35.708 T:874     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'IPV4'
                                                   Traceback (most recent call last):
                                                     File "/usr/share/kodi/addons/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py", line 535, in onAction
                                                       self.update_current_ip_settings(WIRELESS_IP_VALUES)
                                                     File "/usr/share/kodi/addons/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py", line 995, in update_current_ip_settings
                                                       self.current_network_config[self.internet_protocol]['Address'] = ip_address
                                                   KeyError: 'IPV4'
                                                   -->End of Python script error report<--
                                                   
2023-07-29 04:06:41.187 T:843     error <general>: Skipped 6 duplicate messages..
2023-07-29 04:06:41.187 T:843     error <general>: CCurlFile::CReadState::FillBuffer - (0xf0b55128) Failed: Couldn't resolve host name(6)
2023-07-29 04:06:41.187 T:843     error <general>: CCurlFile::Open - <https://download.osmc.tv/kodi/addons/nexus/addons.xml.gz?sha256> Failed with code 0:
                                                   
2023-07-29 04:06:41.187 T:843     error <general>: CRepository: failed read 'https://download.osmc.tv/kodi/addons/nexus/addons.xml.gz?sha256'
2023-07-29 04:06:41.189 T:874     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'IPV4'
                                                   Traceback (most recent call last):
                                                     File "/usr/share/kodi/addons/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py", line 535, in onAction
                                                       self.update_current_ip_settings(WIRELESS_IP_VALUES)
                                                     File "/usr/share/kodi/addons/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py", line 995, in update_current_ip_settings
                                                       self.current_network_config[self.internet_protocol]['Address'] = ip_address
                                                   KeyError: 'IPV4'
                                                   -->End of Python script error report<--

**Comment by samnazarko** [comment]
Please start a support request on forums with full logs.

On 30 Jul 2023, at 03:35, Arndorferd ***@***.***> wrote:

﻿

Cant connect to wifi getting this error in logs

2023-07-29 04:06:21.681 T:557 info : Loading skin file: Settings.xml, load type: KEEP_IN_MEMORY
2023-07-29 04:06:25.294 T:557 info : Loading skin file: /usr/share/kodi/addons/service.osmc.settings/resources/skins/Default/1080i/settings_gui.xml, load type: LOAD_ON_GUI_INIT
2023-07-29 04:06:25.432 T:667 error : EXCEPTION: Non-Existent Control 300
2023-07-29 04:06:27.167 T:557 info : Loading skin file: /usr/share/kodi/addons/script.module.osmcsetting.networking/resources/skins/Default/1080i/network_gui.xml, load type: LOAD_ON_GUI_INIT
2023-07-29 04:06:35.708 T:874 error : EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'KeyError'>
Error Contents: 'IPV4'
Traceback (most recent call last):
File "/usr/share/kodi/addons/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py", line 535, in onAction
self.update_current_ip_settings(WIRELESS_IP_VALUES)
File "/usr/share/kodi/addons/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py", line 995, in update_current_ip_settings
self.current_network_config[self.internet_protocol]['Address'] = ip_address
KeyError: 'IPV4'
-->End of Python script error report<--

2023-07-29 04:06:41.187 T:843 error : Skipped 6 duplicate messages..
2023-07-29 04:06:41.187 T:843 error : CCurlFile::CReadState::FillBuffer - (0xf0b55128) Failed: Couldn't resolve host name(6)
2023-07-29 04:06:41.187 T:843 error : CCurlFile::Open - https://download.osmc.tv/kodi/addons/nexus/addons.xml.gz?sha256 Failed with code 0:

2023-07-29 04:06:41.187 T:843 error : CRepository: failed read 'https://download.osmc.tv/kodi/addons/nexus/addons.xml.gz?sha256'
2023-07-29 04:06:41.189 T:874 error : EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'KeyError'>
Error Contents: 'IPV4'
Traceback (most recent call last):
File "/usr/share/kodi/addons/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py", line 535, in onAction
self.update_current_ip_settings(WIRELESS_IP_VALUES)
File "/usr/share/kodi/addons/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py", line 995, in update_current_ip_settings
self.current_network_config[self.internet_protocol]['Address'] = ip_address
KeyError: 'IPV4'
-->End of Python script error report<--
